---
bool communicationFailure
uint32 rotateCounter
uint32 driveCounter
uint32 injectCounter
uint32 rotateThresh
uint32 driveOnThresh
uint32 driveOffThresh
uint32 injectThresh
uint16 rotateTimeout
uint16 driveOnTimeout
uint16 driveOffTimeout
uint16 injectTimeout
uint16 rotateMaxCurrent
uint16 driveOnMaxCurrent
uint16 driveOffMaxCurrent
uint16 injectMaxCurrent
uint8  rotateStallCheckEnable
uint8  driveOnStallCheckEnable
uint8  driveOffStallCheckEnable
uint8  injectStallCheckEnable