Header header

uint8 currentOpCode
uint8 opCodeOfLastAction

uint8 remainingInjections

uint8 calibrated
uint8 hatchOpen
uint8 wheelInPosition
uint8 driverForward
uint8 driverBack
uint8 fireDanger
uint8 criticalFireDanger

uint8 hatchFailure
uint8 wheelFailure
uint8 driverFailure
uint8 injectorFailure

uint8 rotateMotorOn
uint8 driveMotorOn
uint8 injectMotorOn

uint32 batteryVoltage
uint32 actionStartTime
uint32 actionDuration
uint32 counterStartVal
uint32 counterEndVal
uint16 instantaneousCurrent
uint16 lowestCurrent
uint16 highestCurrent
uint32 totalCurrent